server:
  servlet:
    session:
      cookie:
        same-site: none

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tp.liveamonth@gmail.com
    password: qsjriazlimmitdir
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        mime:
          charset: UTF-8
        transport:
          protocol: smtp
        debug: false

  config:
    import: classpath:auth.yml
  profiles:
    include:
      - auth
    group:
      local: local-server
      test: test-server

---
spring:
  config:
    activate:
      on-profile: local-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/liveamonth-kotlin?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        show_sql: true
    open-in-view: true

  redis:
    host: localhost
    port: 6379
    password:

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: test-server

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 500
        format_sql: true
    open-in-view: true
    show-sql: true

  redis:
    host: localhost
    port: 6379
    password:
